### ISSUE TITLE
how to install torch==1.10.0a0+3fd9dcf

### ISSUE THREAD

**Issue by cssddnnc9527** [nv-tlabs/editGAN_release#2]
Dear author,

thanks for your great contribution, while config the environment,
I encounter an issue as follows:

_pip install torch==1.10.0a0+3fd9dcf
ERROR: Could not find a version that satisfies the requirement torch==1.10.0a0+3fd9dcf (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.10.0a0+3fd9dcf_

Any advice is appreciated!

**Comment by cssddnnc9527** [comment]
Then I install torch through "pip install torch-1.10.0+cu102-cp38-cp38-linux_x86_64.whl", but got the following errors while running run_app.py:

_/home/mashaoming/.conda/envs/editgan/bin/python /media/mashaoming/t2/code/editGAN_release-release_final/run_app.py
Traceback (most recent call last):
  File "/media/mashaoming/t2/code/editGAN_release-release_final/run_app.py", line 26, in <module>
    from utils.model_utils import *
  File "/media/mashaoming/t2/code/editGAN_release-release_final/utils/model_utils.py", line 24, in <module>
    from models.stylegan2_pytorch.stylegan2_pytorch import Generator as Stylegan2Generator
  File "/media/mashaoming/t2/code/editGAN_release-release_final/models/stylegan2_pytorch/stylegan2_pytorch.py", line 6, in <module>
    from models.stylegan2_pytorch.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/media/mashaoming/t2/code/editGAN_release-release_final/models/stylegan2_pytorch/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/media/mashaoming/t2/code/editGAN_release-release_final/models/stylegan2_pytorch/op/fused_act.py", line 11, in <module>
    fused = load(
  File "/home/mashaoming/.conda/envs/editgan/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/home/mashaoming/.conda/envs/editgan/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1362, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/mashaoming/.conda/envs/editgan/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1752, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: /home/mashaoming/.cache/torch_extensions/py38_cu102/fused/fused.so: cannot open shared object file: No such file or directory

Process finished with exit code 1_

**Comment by arieling** [comment]
what's your cuda version and system env?

**Comment by cssddnnc9527** [comment]
@arieling My cuda version is 11.5.1, what do you mean by system env?

**Comment by arieling** [comment]
I don't think cuda 11.5.1 is supported.  The code is tested with CUDA 10.1 toolkit with Pytorch==1.4.0 and CUDA 11.4 with Pytorch==1.10.0.

Check pytorch install doc at https://pytorch.org/get-started/previous-versions/

**Comment by atseewal** [comment]
I think the torch version in the requirements is an old alpha version. The version number has that **a** in it for alpha. Maybe old alphas aren't available? The +3fd9dcf might mean that the version was built from source, but I'm not as sure about that.

> I don't think cuda 11.5.1 is supported

I am running CUDA 11.6. I was able to install torch and torchvision for that CUDA version using the instructions here: [https://pytorch.org/get-started/locally/](https://pytorch.org/get-started/locally/).

`$ pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113 --no-cache-dir --upgrade` is what I used. I ended up with torch==1.11.0+cu113.

**Comment by arieling** [comment]
Thanks! 

> I think the torch version in the requirements is an old alpha version. The version number has that **a** in it for alpha. Maybe old alphas aren't available? The +3fd9dcf might mean that the version was built from source, but I'm not as sure about that.
> 
> > I don't think cuda 11.5.1 is supported
> 
> I am running CUDA 11.6. I was able to install torch and torchvision for that CUDA version using the instructions here: https://pytorch.org/get-started/locally/.
> 
> `$ pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu113 --no-cache-dir --upgrade` is what I used. I ended up with torch==1.11.0+cu113.
